create table m_brands
(
    id   bigint generated by default as identity
        constraint m_brands_pkey
            primary key,
    name varchar(255) not null unique
);

alter table m_brands
    owner to postgres;

create table m_models
(
    id       bigint generated by default as identity
        constraint m_models_pkey
            primary key,
    name     varchar(255) not null unique,
    brand_id bigint       not null
        constraint fklvm12esm6e6jhdcxstcw3iwro
            references m_brands
);

alter table m_models
    owner to postgres;

create table m_cars
(
    id        bigint generated by default as identity
        constraint m_cars_pkey
            primary key,
    mileage   integer,
    photo_url varchar(255),
    vin_code  varchar(17) not null unique,
    year      integer     not null,
    brand_id  bigint      not null
        constraint fkk4exv2ly7wplw6xvjjq497wf1
            references m_brands,
    model_id  bigint      not null
        constraint fkruaoibrddfcxq73syqlyj67a4
            references m_models
);

alter table m_cars
    owner to postgres;



