spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true

# AWS S3 configuration
aws:
  s3:
    accessKeyId: access_key
    secretAccessKey: secret_key
    bucket: bucket
    region: eu-west-1