spring:
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    url: ${DATABASE_URLL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:/migrations
    baseline-on-migrate: true
    baseline-description: <<Flyway Scripts>>
    ignore-missing-migrations: true

  mail:
    default-encoding: UTF-8
    host: ${MAIL_HOST:host}
    host_address: ${HOST_ADDRESS:address}
    username: ${MAIL_USERNAME:username}
    password: ${MAIL_PASSWORD:password}
    port: ${MAIL_PORT:545454884}

aws:
  s3:
    images:
      accessKeyId: ${AWS_ACCES_KEY:key}
      secretAccessKey: ${AWS_SECRET_KEY:secret}
      region: ${AWS_REGION:region}
      bucketName: ${AWS_BUCKET_NAME:bucket}
      carFolderName: ${AWS_CAR_FOLDER_NAME:folder}
      defaultCarImage: ${DEFAULT_CAR_IMAGE:.url}

springdoc:
  packages-to-scan: com.godeltech.mastery.backend.rest
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true

jwt:
  token:
    secret: ${JWT_SECRET:secret}
    expiration: ${JWT_EXPIRATION:86000000}
    issuer: ${JWT_ISSUER:api}
    audience: ${JWT_AUDIENCE:app}

security:
  auth:
    whitelist: >
      /,
      /api-docs
      /v3/api-docs,
      /swagger-ui.html,
      /swagger-ui/**,
      /swagger-resources/**,
      /static/**,
      /api-docs/**,
      /templates/**,
      /swagger-resources/**,
      /index.html,
      /favicon.ico

tinify:
  key: ${TINIFY_SECRET_KEY:key}