spring:
  main:
    banner-mode: off
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/test_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

aws:
  s3:
    images:
      accessKeyId: ${AWS_ACCES_KEY:key}
      secretAccessKey: ${AWS_SECRET_KEY:secret}
      region: ${AWS_REGION:region}
      bucketName: ${AWS_BUCKET_NAME:bucket}
      carFolderName: ${AWS_CAR_FOLDER_NAME:folder}
      defaultCarImage: ${DEFAULT_CAR_IMAGE:.url}

springdoc:
  packages-to-scan: com.godeltech.mastery.backend.rest
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true